laba3-war/src/java/cdi/CdiBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cdi;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import beans_a.*;
import beans_b.*;
import entity_a.*;
import entity_b.*;
import java.util.List;


/**
 *
 * @author пк
 */
@Named("bean")
@SessionScoped
public class CdiBean implements Serializable {
    @EJB
    private TransactionBeanLocal transactionBean;
    
    @EJB
    private ClientFacade clientFacade;
    
    @EJB
    private ContactFacade contactFacade;
    
    private Client client;
    private Contact contact;
    private String name ="";
    private String surname ="";
    private String address ="";
    private String phone ="";

    public List<Client> getAllClients()
    {
        return clientFacade.findAll();
    }
    
    public List<Contact> getAllContacts()
    {
        return contactFacade.findAll();
    }
    public String addToSecondDatabase()
    {
        contact = new Contact(phone, address,0);
        contactFacade.createContact(contact);
        return "/index.xhtml";
    }
    
    public String executeTransactionSuccess()
    {
        client = new Client(name, surname);
      //  System.out.println("new client"+client.getName()+" "+ client.getSurname());
        contact = new Contact(phone, address, 0);
       // System.out.println("new contact"+ contact.getAddress()+" "+contact.getPhone()+" "+ contact.getIdClient());
        transactionBean.ex1(client, contact);
        return "/index.xhtml";
        
    }
    
    public String rollbackFirstDB()
    {
        client = new Client(name, surname);
        contact = new Contact(phone, address, 0);
        transactionBean.ex2(client, contact);
        return "/index.xhtml";
    }
    
    public String throwExeptionSecondDB()
    {
        client = new Client(name, surname);
        contact = new Contact(phone, address, 0);
        transactionBean.ex3(client, contact);
        return "/index.xhtml";
    }
    
    public String executeTransactionNotSupported()
    {
        client = new Client(name, surname);
        contact = new Contact(phone, address, 0);
        transactionBean.ex4(client, contact);
        return "/index.xhtml";
    }
    
    public String executeTransactionNewContext()
    {
        client = new Client(name, surname);
        contact = new Contact(phone, address, 0);
        transactionBean.ex5(client, contact);
        return "/index.xhtml";
    }
    
    public TransactionBeanLocal getTransactionBean() {
        return transactionBean;
    }

    public void setTransactionBean(TransactionBeanLocal transactionBean) {
        this.transactionBean = transactionBean;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Contact getContact() {
        return contact;
    }

    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    
}

laba3-war/web/db2.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:form>
            <h:outputLabel value="phone" for="phone"/><br></br>
            <h:inputText id="phone" value="#{bean.phone}"/><br></br>
            <h:outputLabel value="address" for="address"/><br></br>
            <h:inputText id="address" value="#{bean.address}"/><br></br>
            <br></br>
            добавить только во 2 бд <br></br>
            <h:commandButton id="ex6" value="ex5" action="#{bean.addToSecondDatabase()}"/>
        </h:form>
    </h:body>
</html>

laba3-war/web/example.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:form>
            <h:outputLabel value="name" for="name"/><br></br>
            <h:inputText id="name" value="#{bean.name}"/><br></br>
            <h:outputLabel value="surname" for="surname"/><br></br>
            <h:inputText id="surname" value="#{bean.surname}"/><br></br>
            <h:outputLabel value="phone" for="phone"/><br></br>
            <h:inputText id="phone" value="#{bean.phone}"/><br></br>
            <h:outputLabel value="address" for="address"/><br></br>
            <h:inputText id="address" value="#{bean.address}"/><br></br>
            <br></br>
            Закончить транзакцию подтверждением и убедиться,<br></br>
            что обновления зафиксированы."<br></br>
            <h:commandButton id="ex1" value="ex1" action="#{bean.executeTransactionSuccess()}"/>
            <br></br>
            закончить транзакцию откатом в сессионном фасаде<br></br>
            для первой базы данных и убедиться, что обновления отменены." <br></br>
            <h:commandButton id="ex2" value="ex2" action="#{bean.rollbackFirstDB()}"/>
            <br></br>
            закончить транзакцию откатом, выбросив системное исключение<br></br>
            EJBException в сессионном фасаде для второй базы данных после<br></br>
            обновления источника данных, и убедиться, что обновления отменены." <br></br>
            <h:commandButton id="ex3" value="ex3" action="#{bean.throwExeptionSecondDB()}"/>
            <br></br>
            закончить транзакцию откатом в сессионном фасаде для первой базы данных,<br></br>
            но обновление второй базы данных должно выполняться вне контекста транзакции." <br></br>
            <h:commandButton id="ex4" value="ex4" action="#{bean.executeTransactionNotSupported()}"/>
            <br></br>
            закончить транзакцию откатом, выбросив системное исключение EJBException<br></br>
            в сессионном фасаде для второй базы данных, но обновление первой базы данных<br></br>
            должно выполняться в контексте новой транзакции."<br></br>
            <h:commandButton id="ex5" value="ex5" action="#{bean.executeTransactionNewContext()}"/>
            <br></br>
            добавить только во 2 бд <br></br>
            <h:commandButton id="ex6" value="ex5" action="#{bean.addToSecondDatabase()}"/>
        </h:form>
    </h:body>
</html>

laba3-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <!--
    To change this license header, choose License Headers in Project Properties.
    To change this template file, choose Tools | Templates
    and open the template in the editor.
    -->
    <h:head>
        <title>index</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <f:view>   
            <tr>
            </tr>
            <h:form >
               1 DataBase
                <table cellspacing="1" cellpadding="1"  width="80%" border="1" >  
                    <tr>
                        <td> id_client </td>
                        <td> name </td> 
                        <td> surname </td>
                    </tr> 
                    <c:forEach items="#{bean.allClients}" var="cl">
                        <tr> 
                            <td> #{cl.idClient} </td>
                            <td> #{cl.name} </td> 
                            <td> #{cl.surname} </td>
                        </tr> 
                    </c:forEach>
                </table>
                <br></br>
                2 DataBase
                <br></br>
                <table border="1" >
                    <tr>
                        <td> id </td>
                        <td> address </td> 
                        <td> phone </td>
                        <td> id_client </td>
                    </tr>  
                    <c:forEach items="#{bean.allContacts}" var="contact">
                        <tr> 
                            <td> #{contact.id} </td>
                            <td> #{contact.address} </td>  
                            <td> #{contact.phone} </td> 
                            <td> #{contact.idClient} </td> 
                        </tr> 
                    </c:forEach>
                </table> 
                <h:commandButton value="К экспериментам" action="/example.xhtml"/>
            </h:form>
        </f:view>
    </h:body>
</html>